[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "mobility_advanced_item_dialog"
version = "0.0.1"
description = "Mobility Advanced Item Dialog"
readme = "README.md"
license = { file = "license.txt" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
# You can define dynamic fields if you want setuptools to read them automatically 
# dynamic = ["dependencies"]

dependencies = [
    # TODO: Copy the contents of your requirements.txt file here.
    # For example:
    # "frappe>=14.0.0"
]

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"


[project.urls]
Homepage = "https://github.com/yourusername/mobility_advanced_item_dialog"
